###
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "Yahyo",
  "email": "yahyobafoyev@gmail.com",
  "password": "1234567890"
}

### verify
POST localhost:8080/api/v1/auth/verify
Content-Type: application/json

{
  "email": "yahyobafoyev@gmail.com",
    "code": "684301"
}

### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "asliddinowv@gmail.com",
  "password": "newPassword123"
}

### Request Password Reset
POST localhost:8080/api/v1/auth/request-password-reset
Content-Type: application/json

{
    "email": "asliddinowv@gmail.com"
}

### Reset Password
POST localhost:8080/api/v1/auth/reset-password
Content-Type: application/json

{
  "email": "asliddinowv@gmail.com",
  "code": "636047",
  "newPassword": "newPassword123"
}

### Change Password
POST localhost:8080/api/v1/auth/changePass
Content-Type: application/json

{
  "email": "asliddinowv@gmail.com",
  "oldPassword": "zohirbek",
  "newPassword": "newPassword123"
}

