### Create Inventory
POST http://localhost:8080/api/v1/inventory
Content-Type: application/json

{
  "quantityInStock": 100,
  "productId": "3c43e3bd-a809-4f5b-91ff-358512464de7"
}

### Get Inventory by ID
GET http://localhost:8080/api/v1/inventory/dc2f0ccd-2c24-4857-ac7f-2ec897583836

### Get All Inventory
GET http://localhost:8080/api/v1/inventory?page=0&size=10

### Update Inventory
PUT http://localhost:8080/api/v1/inventory/dc2f0ccd-2c24-4857-ac7f-2ec897583836
Content-Type: application/json

{
  "quantityInStock": 150,
  "productId": "7f1a163a-4843-4f16-84f6-cc1b84b3c223"
}

### Delete Inventory
DELETE http://localhost:8080/api/v1/inventory/dc2f0ccd-2c24-4857-ac7f-2ec897583836

### Get Inventory Alerts (Low Stock)
GET http://localhost:8080/api/v1/inventory/alerts?threshold=10&page=0&size=10

### Get Inventory Movement History
GET http://localhost:8080/api/v1/inventory/movement-history/35b7886d-7702-4343-8ced-6e2d90ed4b70?page=0&size=10

### Update Inventory Quantity
PUT http://localhost:8080/api/v1/inventory/update-quantity/35b7886d-7702-4343-8ced-6e2d90ed4b70?newQuantity=50&movementType=IN
Content-Type: application/json

{
  "quantityInStock": 50,
  "movementType": "IN"
}