### Create Product
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "name": "Tlfoncha",
  "price": 200,
  "description": "o'zim 7 yil ishlatganman zo'r ishlaydi",
  "stockQuantity": 1,
  "supplierId": "cf9b11ad-0183-4195-8900-438ab9e86903"
}

### Get Product by ID
GET http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6

### Get All Products
GET http://localhost:8080/api/v1/product?page=0&size=10

### Update Product
PUT http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 149.99,
  "description": "Updated Product Description",
  "stockQuantity": 150,
  "supplierId": "00675f4c-683d-41ca-8e6d-8033d6ec2f82"
}

### Delete Product
DELETE http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6

### Get Product by Name
GET http://localhost:8080/api/v1/product/search/

### Search Products by Name
GET http://localhost:8080/api/v1/product/search/Test Product?page=0&size=10

### Get Low Stock Products
GET http://localhost:8080/api/v1/product/get-low-stock-products?threshold=10&page=0&size=10


### Get Products by Supplier ID
GET http://localhost:8080/api/v1/product/get-products-by-supplier/00675f4c-683d-41ca-8e6d-8033d6ec2f82?page=0&size=10