### Create Product
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "name": "Test Product",
  "price": 99.99,
  "description": "Test Product Description",
  "stockQuantity": 100,
  "supplierId": "00675f4c-683d-41ca-8e6d-8033d6ec2f82"
}

### Get Product by ID
GET http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6

### Get All Products
GET http://localhost:8080/api/v1/product?page=0&size=10

### Update Product
PUT http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 149.99,
  "description": "Updated Product Description",
  "stockQuantity": 150,
  "supplierId": "00675f4c-683d-41ca-8e6d-8033d6ec2f82"
}

### Delete Product
DELETE http://localhost:8080/api/v1/product/e6d919f8-612a-4062-a309-e7cf3f1b01b6