POST http://localhost:8080/api/v1/supply/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2xpZGRpbm93dkBnbWFpbC5jb20iLCJpYXQiOjE3NDc4MDA4MTcsImV4cCI6MTc0Nzg4NzIxN30.8sCSudyXwGZ8RnBTnZn5HZ-8NMsFVSwX0xzSzkFu5os
Content-Type: application/json

{
  "name": "Sardor",
  "address": "sardor@gmail.com",
  "contact_info": "+998956483719"
}

### GET BY ID
GET http://localhost:8080/api/v1/supply/get-by-id/c0599e0f-eaa9-47c5-83c6-c1cf4795122f
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2xpZGRpbm93dkBnbWFpbC5jb20iLCJpYXQiOjE3NDc4MDA4MTcsImV4cCI6MTc0Nzg4NzIxN30.8sCSudyXwGZ8RnBTnZn5HZ-8NMsFVSwX0xzSzkFu5os

### GET ALL
GET localhost:8080/api/v1/supply/get-all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2xpZGRpbm93dkBnbWFpbC5jb20iLCJpYXQiOjE3NDc4MDA4MTcsImV4cCI6MTc0Nzg4NzIxN30.8sCSudyXwGZ8RnBTnZn5HZ-8NMsFVSwX0xzSzkFu5os

#### update
PUT http://localhost:8080/api/v1/supply/update/c0599e0f-eaa9-47c5-83c6-c1cf4795122f
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhc2xpZGRpbm93dkBnbWFpbC5jb20iLCJpYXQiOjE3NDc4MDE0NTcsImV4cCI6MTc0Nzg4Nzg1N30.JO79ZdO5wEeNU7bjDKDqTEqB6ELySj_sYp-OLZlXGRw
Content-Type: application/json

{
  "name": "Yoq",
  "address": "No Address",
  "contact_info": "no info"
}

### DELETE
DELETE http://localhost:8080/api/v1/supply/delete/c0599e0f-eaa9-47c5-83c6-c1cf4795122f
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhc2xpZGRpbm93dkBnbWFpbC5jb20iLCJpYXQiOjE3NDc4MDE0NTcsImV4cCI6MTc0Nzg4Nzg1N30.JO79ZdO5wEeNU7bjDKDqTEqB6ELySj_sYp-OLZlXGRw