### CREATE SUPPLIER
POST localhost:8080/api/v1/supply/add
Content-Type: application/json

{
  "name": "Bexruz",
  "address": "Mars",
  "contact_info": "+998999999999"
}

### GET BY ID
GET localhost:8080/api/v1/supply/get-by-id/9de06c73-dc35-4261-8843-9ba1ad3a5b5f

### GET ALL
GET localhost:8080/api/v1/supply/get-all

### UPDATE
PUT localhost:8080/api/v1/supply/update/9de06c73-dc35-4261-8843-9ba1ad3a5b5f
Content-Type: application/json

{
"name": "Yoq",
  "address": "No Address",
  "contact_info": "no info"
}

### DELETE
DELETE localhost:8080/api/v1/supply/delete/00675f4c-683d-41ca-8e6d-8033d6ec2f82