### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "zohir",
  "email": "zohir@gmail.com",
  "password": "zohir123"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "zohir@gmail.com",
  "password": "zohir123"
}

### Get User Profile
GET http://localhost:8080/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXJkb3JAZ21haWwuY29tIiwiaWF0IjoxNzQ3NjcyMzEzLCJleHAiOjE3NDc3NTg3MTN9.lCBH3dmnWyTkx0Mn-NXDCN5q4wmaqx4NiC3JS9HBsr4

### Update User Profile
PUT http://localhost:8080/api/v1/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6b2hpckBnbWFpbC5jb20iLCJpYXQiOjE3NDc2NzIzNzgsImV4cCI6MTc0Nzc1ODc3OH0.9y1fjtrd_YeYL2srFzlrXGS77pUmJOeBk5dNwgRILoM
Content-Type: application/json

{
  "fullName": "ZOHIR",
  "email": "asliddinov@example.com",
  "password": "NEWZOHIR123"
}

### Get All Users (Admin only)
GET http://localhost:8080/api/v1/user?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXJkb3JAZ21haWwuY29tIiwiaWF0IjoxNzQ3NjcyMzEzLCJleHAiOjE3NDc3NTg3MTN9.lCBH3dmnWyTkx0Mn-NXDCN5q4wmaqx4NiC3JS9HBsr4

### Get User by ID (Admin only)
GET http://localhost:8080/api/v1/user/377a201d-595a-4e76-b2e3-b284b1c2ccd1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXJkb3JAZ21haWwuY29tIiwiaWF0IjoxNzQ3NjcyMzEzLCJleHAiOjE3NDc3NTg3MTN9.lCBH3dmnWyTkx0Mn-NXDCN5q4wmaqx4NiC3JS9HBsr4

### Delete User (Admin only)
DELETE http://localhost:8080/api/v1/user/32286045-3d5e-4a99-9069-6a7fcc3891f9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXJkb3JAZ21haWwuY29tIiwiaWF0IjoxNzQ3NjcyMzEzLCJleHAiOjE3NDc3NTg3MTN9.lCBH3dmnWyTkx0Mn-NXDCN5q4wmaqx4NiC3JS9HBsr4

### Create Store (Store Owner only)
POST http://localhost:8080/api/v1/store/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6b2hpckBnbWFpbC5jb20iLCJpYXQiOjE3NDc3MTAzOTcsImV4cCI6MTc0Nzc5Njc5N30.PjLgLXmblAstsQDjOjkNuz_w-5U6Ssi-jb87kn9ys3E
Content-Type: application/json

{
  "name": "My Store",
  "address": "Earth",
  "phone": "77 777 77 77"
}

### Get My Stores (Store Owner only)
GET http://localhost:8080/api/v1/store/my-stores
Authorization: Bearer {{token}}

### Create Staff (Store Owner only)
POST http://localhost:8080/api/v1/staff/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fullName": "Staff Member",
    "email": "staff@example.com",
    "password": "staff123",
    "storeId": "{{storeId}}"
}

### Get My Staff (Store Owner only)
GET http://localhost:8080/api/v1/staff/my-staff
Authorization: Bearer {{token}}

### Create Product (Store Owner or Admin only)
POST http://localhost:8080/api/v1/product/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Product Name",
    "description": "Product Description",
    "price": 99.99,
    "quantity": 100,
    "storeId": "{{storeId}}"
}

### Get My Products (Store Owner or Admin only)
GET http://localhost:8080/api/v1/product/my-products
Authorization: Bearer {{token}}

### Create Order (User or Staff only)
POST http://localhost:8080/api/v1/order/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": 2,
    "address": "Delivery Address"
}

### Get My Orders (User or Staff only)
GET http://localhost:8080/api/v1/order/my-orders
Authorization: Bearer {{token}}